import ExperienceCard from "../../components/experience-card/experience-card.component";
import TitleSection from "../../components/title-section/title-section.component";
import { ExperiencesContainer, Experience } from "./experiences.styles";

const experiences = [
	{
		company: "Lollier Ingénierie",
		title: "Assistant Project Manager",
		description: `I have worked on developing various IT tools in the field of project management and administration:

– Developed a plugin for the open-source software QGIS to automate the extraction of cartographic data. I primarily developed this tool in Python, using libraries such as requests, BeautifulSoup, etc. Then, I worked on formatting the extracted data to export it in Word format (python-docx library).

– Development of a management tool in Microsoft Excel to centralize the data from quotes generated by the different branches of the company. The code for this tool was written in VBA (Visual Basic for Applications), a language integrated into Excel.

– Worked with the open-source software WebODM to develop a code allowing users to process and merge images taken with a drone, resulting in an orthophoto.`,
		imgURL: "https://i.ibb.co/wFRQt9dy/lollier-logo.png",
	},
	{
		company: "Pathé Cinéma",
		title: "Assistant Project Manager",
		description: `Tracking the Evolution of Digital Products (App/Web):
– Conducted thorough testing of both mobile and web applications to ensure all elements were up-to-date and functioning correctly.
– Performed cross-device and cross-platform testing prior to new version releases, ensuring compatibility and performance across a variety of devices (iOS, Android, tablets, desktop browsers, etc.).
– Monitored and analyzed user comments and feedback to identify recurring issues and usability concerns.
– Reported bugs clearly and effectively, prioritizing their resolution based on user impact and development timelines.`,
		imgURL: "https://i.ibb.co/7xvY3tf0/pathe-logo.webp",
	},
	{
		company: "BDE EMSE CGCP",
		title: "President",
		description: `President of the Student Union:
– Managed the budget for student activities with a strong focus on optimizing fund allocation to maximize the number and quality of events organized throughout the academic year.
– Led and coordinated a diverse team responsible for planning, organizing, and executing various student events, ensuring smooth operations while carefully balancing costs and resources.
– Gained practical experience in financial management, including budgeting, expense tracking, and financial reporting, to maintain transparency and accountability.
– Served as the primary liaison between student associations and the University administration, facilitating communication, fostering collaboration, and ensuring that student groups received necessary support and resources.
– Developed strong leadership, teamwork, and organizational skills through managing both people and projects in a dynamic, fast-paced environment.`,
		imgURL: "https://i.ibb.co/xK017z6p/bde-logo.jpg",
	},
];

const Experiences = () => {
	return (
		<div id="experiences">
			<ExperiencesContainer>
				<TitleSection>Experiences</TitleSection>
				<Experience>
					{experiences.map((experience) => (
						<ExperienceCard
							key={experience.company}
							experienceCard={experience.company}
							title={experience.title}
							description={experience.description}
							imgURL={experience.imgURL}
						/>
					))}
				</Experience>
			</ExperiencesContainer>
		</div>
	);
};

export default Experiences;
